version: '3.6'

volumes:
  exec_data:
  pgdata:
  keycloak_pgdata:

services:
  # LEQO Framework API
  # This one should be the image created by the workflow on the bloqcat repo
  leqo-api:
    image: leqo/framework-api:latest
    ports:
      - "5000:5000"
    networks:
      - leqo-network

  # LEQO Model Repository (Winery Replacement)
  # in the bloqcat-modeling worklfow
  leqo-model-repo:
    image: leqo/model-repo:latest
    environment:
      LEQO_HOSTNAME: ${PUBLIC_HOSTNAME}
      REPOSITORY_URL: https://github.com/leqo/model-repo
    ports:
      - "8080:8080"
    networks:
      - leqo-network

  # LEQO Database (Postgres Replacement for QC-Atlas and Pattern Atlas)
  # Need to be created locally everytime so no workflow needed
  leqo-db:
    image: leqo/database:latest
    environment:
      LEQO_USERS: 'user1:password1|user2:password2'
      LEQO_DATABASES: 'db1:db1|db2:db2'
      MAIN_DB: db1
      SECONDARY_DB: db2
    ports:
      - "5060:5060"
    networks:
      - leqo-network

  # LEQO UI
  # created in qc-atlas-ui workflow
  leqo-ui:
    image: leqo/framework-ui:latest
    depends_on:
      - leqo-config-server
    environment:
      LEQO_API_HOST: localhost
      LEQO_API_PORT: 6626
    ports:
      - "80:80"
    networks:
      - leqo-network

  # LEQO Authentication (Keycloak Replacement)
  # NOT change
  leqo-auth:
    image: leqo/auth-service:latest
    environment:
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
    ports:
      - "7080:8080"
    networks:
      - leqo-network

  # LEQO Config Server (ETCD Replacement)
  # NOT replace this one. This is needed as the config server and should be the q...
  leqo-config-server:
    image: leqo/config-server:latest
    environment:
      CONFIG_NAME: leqo-config-node
      CONFIG_CORS: "*"
      CONFIG_URL: "http://leqo-config-server:2379"
    ports:
      - "2379:2379"
    networks:
      - leqo-network

  # LEQO Qunicorn Server (Quantum Job Handler)
  # You dont need that
  leqo-qunicorn:
    image: leqo/qunicorn:latest
    environment:
      MODE: server
      SERVER_PORT: 5005
      BROKER_URL: "redis://leqo-broker:6379"
      DB_URL: "postgresql://postgres:passwd@leqo-db/qunicorn"
      JWKS_URL: "http://leqo-auth:8081/auth/realms/qunicorn/protocol/openid-connect/certs"
    depends_on:
      - leqo-db
      - leqo-broker
      - leqo-worker
    ports:
      - "5005:5005"
    networks:
      - leqo-network

  # LEQO Worker (Job Processor)
  # You dont need that
  leqo-worker:
    image: leqo/worker:latest
    environment:
      MODE: worker
      BROKER_URL: "redis://leqo-broker:6379"
      DB_URL: "postgresql://postgres:passwd@leqo-db/qunicorn"
    depends_on:
      - leqo-db
      - leqo-broker
    ports:
      - "6379"
    networks:
      - leqo-network

  # LEQO Message Broker (Redis Replacement)
  # You dont need that
  leqo-broker:
    image: leqo/broker:latest
    ports:
      - "6379:6379"
    networks:
      - leqo-network

  # LEQO Renderer (LaTeX Service Replacement)
  # Dont think you need to change that (from the original one)
  leqo-renderer:
    image: leqo/renderer:latest
    ports:
      - "5030:5030"
    networks:
      - leqo-network

networks:
  leqo-network:
    driver: bridge
